### ISSUE TITLE
Wrong audio track selected so I can't hear the presenter audio when editing

### ISSUE THREAD

**Issue by slaudel** [opencast/opencast-editor#1475]
We upgraded to Opencast 16 this summer. Now that the lectures have started again, we can not cut our automatic recordings because we can't hear the presenter audio.
I refer to my posting on the google list: [https://groups.google.com/a/opencast.org/g/users/c/sou65c6oFGA](https://groups.google.com/a/opencast.org/g/users/c/sou65c6oFGA).

I know what the problem is, but can not solve it. The recorded presentation file also contains an audio stream which mostly is empty, but sometimes could contain the presentation/computer audio.
So I think, the editor should better pick the presenter file for audio or needs a switch so one could switch between both tracks.

Could I manually tell the editor to use the presenter audio? Or could I switch to the old editor? I need to cut the recordings.

On the google list #1376 was mentioned, but this does not work for us, because as I wrote, both recordings contain an audio track.

**Comment by mtneug** [comment]
IMO, those problems should be solved beforehand in the workflow. E.g. you can remove the audio stream from the presentation track. IMO, the editor should not make an assumption about what audio stream the primary is.

**Comment by slaudel** [comment]
Why not make the assumption and take the presenter as the audio?
So now if both files contain an audio, i think it's always the presentation file which provides the audio. I think because "presentation" is before "presenter" lexically. Or maybe it's non deterministic? 
Or why not make it selectable in the editor? 

Else could you please provide me with an example workflow to remove the audio from the presentation file?

**Comment by mtneug** [comment]
Sorry, @slaudel, I didn't have time to answer (I have seen your mail and the comment here).

So this is untested, but this should remove the audio track from `presentation/source`:

```xml
<operation
    id="tag"
    description="Rename flavor of presentation">
  <configurations>
    <configuration key="source-flavors">presentation/source</configuration>
    <configuration key="target-flavor">presentation/source+original</configuration>
    <configuration key="target-tags">archive</configuration>
  </configurations>
</operation>

<operation
    id="encode"
    description="Remove audio from presentation">
  <configurations>
    <configuration key="source-flavor">presentation/source+original</configuration>
    <configuration key="target-flavor">presentation/source</configuration>
    <configuration key="target-tags">archive</configuration>
    <configuration key="encoding-profile">video-only.copy</configuration>
  </configurations>
</operation>
```

This can be included in your ingest workflow. The original file will still be archived under the flavor `presentation/source+original`.

**Comment by slaudel** [comment]
Thanks @mtneug, I tried it and it worked in that the audio is removed from the (new) presentation. 
**BUT** the editor still does not play the audio! I did find another workflow component to do the same but the result is the same (as I wrote in the google group [https://groups.google.com/a/opencast.org/g/users/c/sou65c6oFGA](https://groups.google.com/a/opencast.org/g/users/c/sou65c6oFGA)).
I updated to opencast 16.6 (yum rpm) a few days ago, so #1376 should be merged.
I attached a screenshot of a recording in the editor.
<img width="1757" alt="Bildschirmfoto 2024-10-22 um 17 50 59" src="https://github.com/user-attachments/assets/a818a1c8-9232-481e-a4fd-9f27373a412a">
